Repository gridhead/gi-loadouts, pull requests merged in 2024-09, with the labels that each got.

#101 Fix the URL of image in README.md
  README.md
Labels: documentation

#102 Fetch artifact name from ArtiList while saving
  gi_loadouts/face/wind/fclt.py
Labels: bug

#103 Rename the SecoStatType members to match the naming convention
  gi_loadouts/type/arti/base/__init__.py
Labels: bug

#115 Move the `Level` drop-down below the `Constellation` drop-down
  assets/wind.ui
  gi_loadouts/face/wind/wind.py
Labels: bug

#114 Rework the documentation with the OCR feature
  README.md
  assets/docs/cash.png
  assets/docs/dark.png
  assets/docs/dark_rslt.png
  assets/docs/docs_arti_data.png
  assets/docs/docs_arti_levl.png
  assets/docs/docs_arti_load.png
  assets/docs/docs_arti_main.png
  assets/docs/docs_arti_rare.png
  assets/docs/docs_arti_save.png
  assets/docs/docs_arti_scan.png
  assets/docs/docs_arti_seco.png
  assets/docs/docs_arti_type.png
  assets/docs/docs_arti_wipe.png
  assets/docs/docs_calc.png
  assets/docs/docs_char_aeth.png
  assets/docs/docs_char_cons.png
  assets/docs/docs_char_levl.png
  assets/docs/docs_char_lumi.png
  assets/docs/docs_char_name.png
  assets/docs/docs_char_vson.png
  assets/docs/docs_scan_conf.png
  assets/docs/docs_scan_dgbx.png
  assets/docs/docs_scan_dtwp.png
  assets/docs/docs_scan_impt.png
  assets/docs/docs_scan_imwp.png
  assets/docs/docs_scan_load.png
  assets/docs/docs_scan_rslt.png
  assets/docs/docs_team_bone.png
  assets/docs/docs_team_load.png
  assets/docs/docs_team_save.png
  assets/docs/docs_team_scan.png
  assets/docs/docs_team_wipe.png
  assets/docs/docs_weap_levl.png
  assets/docs/docs_weap_load.png
  assets/docs/docs_weap_name.png
  assets/docs/docs_weap_refn.png
  assets/docs/docs_weap_save.png
  assets/docs/docs_weap_type.png
  assets/docs/fork.png
  assets/docs/gnul_dark.png
  assets/docs/gnul_dark_rslt.png
  assets/docs/gnul_lite.png
  assets/docs/gnul_lite_rslt.png
  assets/docs/lite.png
  assets/docs/lite_rslt.png
  assets/docs/mswn_dark.png
  assets/docs/mswn_dark_rslt.png
  assets/docs/mswn_lite.png
  assets/docs/mswn_lite_rslt.png
Labels: documentation

#117 Apply logical correction in `SAVE` and `LOAD` for weapons with no refinement
  gi_loadouts/face/wind/fclt.py
Labels: bug

#126 Modify logic of `MAINSTAT` scanning and correct the `REGEX` for ER
  gi_loadouts/face/scan/__init__.py
  gi_loadouts/face/scan/util.py
Labels: bug

#128 Adjust text truncation of artifact names and teams
  gi_loadouts/face/wind/rule.py
Labels: bug

#129 Recommend attempting other screenshots for precision
  README.md
  assets/docs/docs_scan_rslt_01.png
  assets/docs/docs_scan_rslt_02.png
  assets/docs/docs_scan_rslt_03.png
  assets/docs/docs_scan_rslt_04.png
  assets/docs/tckt.png
Labels: documentation

#122 Implement support for the GOOD format
  gi_loadouts/face/wind/fclt.py
  gi_loadouts/face/wind/file.py
  gi_loadouts/type/file/__init__.py
  gi_loadouts/type/file/arti.py
  gi_loadouts/type/file/team.py
  gi_loadouts/type/file/weap.py
  gi_loadouts/type/stat/__init__.py
Labels: enhancement

#134 Add shields and badges to the `README.md`
  README.md
Labels: documentation

#138 Lower the superficial frames distinctiveness
  assets/scan.ui
  assets/wind.ui
  gi_loadouts/face/scan/scan.py
  gi_loadouts/face/wind/wind.py
Labels: bug

#139 Remove invalid icon tooltip from the scanning dialog
  assets/scan.ui
  gi_loadouts/face/scan/scan.py
Labels: bug

#144 Wipe cache left over from previous sessions
  gi_loadouts/face/rsrc/__init__.py
Labels: bug

#142 Rework the documentation after adding GOOD support
  README.md
  assets/info.ui
  gi_loadouts/__init__.py
  gi_loadouts/face/info/info.py
  gi_loadouts/face/info/main.py
  gi_loadouts/face/lcns/main.py
Labels: documentation, enhancement

#147 Move the build target from Ubuntu to Fedora environment
  .github/workflows/gnul.yml
  gi_loadouts/face/scan/rule.py
Labels: bug

#146 Step up compression level and step down retention days
  .github/workflows/gnul.yml
Labels: dependencies

#145 Move the scanning operation to another thread
  gi_loadouts/face/scan/file.py
  gi_loadouts/face/scan/main.py
  gi_loadouts/face/scan/rule.py
  gi_loadouts/face/scan/util.py
  gi_loadouts/face/scan/work.py
  gi_loadouts/face/util.py
Labels: bug

#150 Add new screenshots for the documentation
  README.md
  assets/docs/cash.png
  assets/docs/docs_arti_data.png
  assets/docs/docs_arti_levl.png
  assets/docs/docs_arti_load.png
  assets/docs/docs_arti_main.png
  assets/docs/docs_arti_rare.png
  assets/docs/docs_arti_save.png
  assets/docs/docs_arti_scan.png
  assets/docs/docs_arti_seco.png
  assets/docs/docs_arti_type.png
  assets/docs/docs_arti_wipe.png
  assets/docs/docs_calc.png
  assets/docs/docs_char_aeth.png
  assets/docs/docs_char_cons.png
  assets/docs/docs_char_levl.png
  assets/docs/docs_char_lumi.png
  assets/docs/docs_char_name.png
  assets/docs/docs_char_vson.png
  assets/docs/docs_full.png
  assets/docs/docs_scan_conf.png
  assets/docs/docs_scan_dgbx.png
  assets/docs/docs_scan_dtwp.png
  assets/docs/docs_scan_impt.png
  assets/docs/docs_scan_imwp.png
  assets/docs/docs_scan_load.png
  assets/docs/docs_scan_rslt_01.png
  assets/docs/docs_scan_rslt_02.png
  assets/docs/docs_scan_rslt_03.png
  assets/docs/docs_scan_rslt_04.png
  assets/docs/docs_team_bone.png
  assets/docs/docs_team_load.png
  assets/docs/docs_team_save.png
  assets/docs/docs_team_scan.png
  assets/docs/docs_team_wipe.png
  assets/docs/docs_weap_levl.png
  assets/docs/docs_weap_load.png
  assets/docs/docs_weap_name.png
  assets/docs/docs_weap_refn.png
  assets/docs/docs_weap_save.png
  assets/docs/docs_weap_type.png
  assets/docs/fork.png
  assets/docs/gnul_dark.png
  assets/docs/gnul_dark_rslt.png
  assets/docs/gnul_lite.png
  assets/docs/gnul_lite_rslt.png
  assets/docs/info.png
  assets/docs/lcns.png
  assets/docs/mswn_dark.png
  assets/docs/mswn_dark_rslt.png
  assets/docs/mswn_lite.png
  assets/docs/mswn_lite_rslt.png
  assets/docs/tckt.png
Labels: documentation

#151 Include other authors to the project specification
  pyproject.toml
Labels: documentation

#152 Make minor adjustments to the documentation
  README.md
  assets/docs/docs_char_aeth.png
  assets/docs/docs_char_lumi.png
  assets/docs/docs_weap_load.png
  assets/docs/docs_weap_save.png
Labels: documentation

#157 Version bump from `v0.1.0a2` to `v0.1.0`
  pyproject.toml
Labels: enhancement

#169 Add test for `output` window
  test/face/otpt/__init__.py
  test/face/otpt/test_otpt.py
Labels: bug

#170 Check saving/loading functionality for artifact sets
  test/face/wind/team/test_team_file.py
Labels: bug

#171 Check saving/loading functionality for weapons
  gi_loadouts/type/file/weap.py
  test/face/wind/weap/test_file.py
Labels: bug
