Repository gridhead/gi-loadouts, pull requests merged in 2024-12, with the labels that each got.

#231 Bug report templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#232 Fix issue #163: Fix the tests for the Sword weapon called Sword of De…
  gi_loadouts/type/weap/__init__.py
  test/data/weap/test_sword.py
  test/face/wind/weap/kind/test_sword.py
Labels: bug

#237 Converge the coverage config to the project config
  .coveragerc
  pyproject.toml
  tox.ini
Labels: bug

#238 Correct the compatible version/phase
  gi_loadouts/__init__.py
Labels: enhancement
