Repository gridhead/gi-loadouts, pull requests merged in 2024-11, with the labels that each got.

#201 Fix the GitHub Actions CI after Fedora Linux 41 update
  .github/workflows/test.yml
Labels: dependencies, python

#200 Update the project documentation
  README.md
  assets/docs/cash.png
  assets/docs/docs_arti_data.png
  assets/docs/docs_arti_levl.png
  assets/docs/docs_arti_load.png
  assets/docs/docs_arti_main.png
  assets/docs/docs_arti_rare.png
  assets/docs/docs_arti_save.png
  assets/docs/docs_arti_scan.png
  assets/docs/docs_arti_seco.png
  assets/docs/docs_arti_type.png
  assets/docs/docs_arti_wipe.png
  assets/docs/docs_calc.png
  assets/docs/docs_char_aeth.png
  assets/docs/docs_char_cons.png
  assets/docs/docs_char_levl.png
  assets/docs/docs_char_lumi.png
  assets/docs/docs_char_name.png
  assets/docs/docs_char_vson.png
  assets/docs/docs_scan_conf.png
  assets/docs/docs_scan_dgbx.png
  assets/docs/docs_scan_dtwp.png
  assets/docs/docs_scan_impt.png
  assets/docs/docs_scan_imwp.png
  assets/docs/docs_scan_load.png
  assets/docs/docs_scan_rslt_01.png
  assets/docs/docs_scan_rslt_02.png
  assets/docs/docs_scan_rslt_03.png
  assets/docs/docs_scan_rslt_04.png
  assets/docs/docs_team_bone.png
  assets/docs/docs_team_load.png
  assets/docs/docs_team_save.png
  assets/docs/docs_team_scan.png
  assets/docs/docs_team_wipe.png
  assets/docs/docs_weap_levl.png
  assets/docs/docs_weap_load.png
  assets/docs/docs_weap_name.png
  assets/docs/docs_weap_refn.png
  assets/docs/docs_weap_save.png
  assets/docs/docs_weap_type.png
  assets/docs/fork.png
  assets/docs/info.png
  assets/docs/lcns.png
  assets/docs/mswn_dark.png
  assets/docs/mswn_dark_rslt.png
  assets/docs/mswn_lite.png
  assets/docs/mswn_lite_rslt.png
  assets/docs/tckt.png
Labels: documentation

#202 Add remaining new screenshots after the changes
  assets/docs/docs_arti_load.png
  assets/docs/gnul_dark.png
  assets/docs/gnul_dark_rslt.png
  assets/docs/gnul_lite.png
  assets/docs/gnul_lite_rslt.png
Labels: documentation

#204 Add check for `filepath` to return either `False` or `True`
  gi_loadouts/face/scan/file.py
  test/face/scan/test_scan.py
Labels: bug

#216 Modify CI to run on pull_request as well
  .github/workflows/qlty.yml
  .github/workflows/test.yml
  .github/workflows/wipe.yml
Labels: bug

#220 Update compatible version to v5.1 Phase 2
  gi_loadouts/__init__.py
Labels: enhancement

#225 Update project and compatibility to v5.2 Phase 1
  gi_loadouts/__init__.py
  pyproject.toml
Labels: enhancement
