Repository gridhead/gi-loadouts, pull requests merged in 2024-10, with the labels that each got.

#178 Add test for `scan` window
  .github/workflows/test.yml
  assets/wind.ui
  gi_loadouts/conf.py
  gi_loadouts/face/rsrc/__init__.py
  gi_loadouts/face/scan/rule.py
  gi_loadouts/face/scan/work.py
  gi_loadouts/face/wind/calc.py
  gi_loadouts/face/wind/main.py
  gi_loadouts/face/wind/wind.py
  test/conftest.py
  test/face/scan/__init__.py
  test/face/scan/test_scan.py
  test/static/img/gi-loadouts-ocr-test.webp
Labels: bug

#184 Add tests for the remaining part of the codebase
  gi_loadouts/face/util.py
  gi_loadouts/face/wind/fclt.py
  gi_loadouts/face/wind/main.py
  gi_loadouts/face/wind/talk.py
  gi_loadouts/main.py
  gi_loadouts/type/weap/hpak.py
  test/face/otpt/test_otpt.py
  test/face/scan/__init__.py
  test/face/scan/test_scan.py
  test/face/wind/__init__.py
  test/face/wind/test_wind_main.py
  test/static/gi-loadouts-ocr-test-ccol.png
  test/static/gi-loadouts-ocr-test-fwol.png
  test/static/gi-loadouts-ocr-test-gboe.png
  test/static/gi-loadouts-ocr-test-pmod.png
  test/static/gi-loadouts-ocr-test-sdoe.png
  test/static/img/gi-loadouts-ocr-test.webp
  test/test_main.py
Labels: bug

#187 Add test of type of weapon
  test/type/test_char.py
  test/type/test_levl.py
  test/type/test_rank.py
  test/type/test_rare.py
  test/type/test_stat.py
  test/type/test_vson.py
  test/type/test_weap.py
Labels: bug

#191 Update dependencies lockfile to the latest version
  poetry.lock
Labels: dependencies, python

#196 Add exception handling in the destructor `scan/rule.py`
  gi_loadouts/face/scan/rule.py
Labels: bug

#195 Remove `pytest-memray` from the project dependencies
  poetry.lock
  pyproject.toml
  tox.ini
Labels: dependencies, python

#197 Allow including screenshots from the clipboard using keyboard shortcuts + drag-and-drop
  assets/scan.ui
  gi_loadouts/face/scan/file.py
  gi_loadouts/face/scan/main.py
  gi_loadouts/face/scan/rule.py
  gi_loadouts/face/scan/scan.py
  test/conftest.py
  test/face/scan/__init__.py
  test/face/scan/test_scan.py
Labels: enhancement

#199 Bump version from v0.1.0 to v0.1.1
  poetry.lock
  pyproject.toml
Labels: enhancement
