Repository gridhead/gi-loadouts, pull requests merged in 2025-01, with the labels that each got.

#245 Include codebase testing for Python 3.13 release
  .github/workflows/test.yml
  tox.ini
Labels: enhancement

#249 Correct commentary additions on weapon codebase
  gi_loadouts/data/weap/claymores/miam.py
  gi_loadouts/data/weap/claymores/swpr.py
  gi_loadouts/data/weap/claymores/uoms.py
  gi_loadouts/data/weap/polearms/efln.py
  gi_loadouts/data/weap/polearms/sohm.py
  gi_loadouts/data/weap/polearms/soss.py
Labels: documentation

#256 Include a disclaimer section in the project docs
  README.md
Labels: documentation

#257 Stage the release for Genshin Impact v5.3 Phase 1
  gi_loadouts/__init__.py
  pyproject.toml
Labels: documentation

#258 Add the missing `refi_stat` values for new weapon `Starcaller's Watch`
  gi_loadouts/data/weap/catalysts/scwh.py
Labels: bug

#265 Version bump from v0.1.4 to v0.1.5
  pyproject.toml
Labels: documentation
